"""Initiate database

Revision ID: 8f84fe99a44d
Revises: 
Create Date: 2024-12-22 21:21:05.100590

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '8f84fe99a44d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')

    op.create_table('dim_bioid',
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('bioid', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.PrimaryKeyConstraint('bioid')
    )

    op.create_table('dim_petition',
    sa.Column('id', postgresql.UUID(as_uuid=True), default=sa.text('uuid_generate_v4()')),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('petition_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('petition_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('petitioner', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_petition_petitioner'), 'dim_petition', ['petitioner'], unique=False)

    op.create_table('user',
    sa.Column('id', postgresql.UUID(as_uuid=True), default=sa.text('uuid_generate_v4()')),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)

    op.create_table('dim_user',
    sa.Column('id', postgresql.UUID(as_uuid=True), default=sa.text('uuid_generate_v4()')),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bioid', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), default=sa.text('now()'), autoincrement=False, nullable=True),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['bioid'], ['dim_bioid.bioid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_user_bioid'), 'dim_user', ['bioid'], unique=True)
    op.create_index(op.f('ix_dim_user_email'), 'dim_user', ['email'], unique=True)

    op.create_table('item',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), default=sa.text('uuid_generate_v4()')),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('facts_petition',
    sa.Column('id', postgresql.UUID(as_uuid=True), default=sa.text('uuid_generate_v4()')),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('petition_id', sa.Uuid(), nullable=True),
    sa.Column('petition_affector_id', sa.Uuid(), nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['petition_affector_id'], ['dim_user.id'], ),
    sa.ForeignKeyConstraint(['petition_id'], ['dim_petition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_petition_action'), 'facts_petition', ['action'], unique=False)
    op.create_index(op.f('ix_facts_petition_petition_affector_id'), 'facts_petition', ['petition_affector_id'], unique=False)
    op.create_index(op.f('ix_facts_petition_petition_id'), 'facts_petition', ['petition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facts_petition_petition_id'), table_name='facts_petition')
    op.drop_index(op.f('ix_facts_petition_petition_affector_id'), table_name='facts_petition')
    op.drop_index(op.f('ix_facts_petition_action'), table_name='facts_petition')
    op.drop_table('facts_petition')
    op.drop_table('item')
    op.drop_index(op.f('ix_dim_user_email'), table_name='dim_user')
    op.drop_index(op.f('ix_dim_user_bioid'), table_name='dim_user')
    op.drop_table('dim_user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_dim_petition_petitioner'), table_name='dim_petition')
    op.drop_table('dim_petition')
    op.drop_table('dim_bioid')
    # ### end Alembic commands ###
