"""Initiate database

Revision ID: f5d0bad39ebe
Revises: 
Create Date: 2025-01-13 04:00:00.125370

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f5d0bad39ebe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_petitionthreshold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vote_threshold', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dim_user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_user_email'), 'dim_user', ['email'], unique=True)
    op.create_table('user',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('dim_bioid',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('bioid', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['dim_user.id'], ),
    sa.PrimaryKeyConstraint('bioid')
    )
    op.create_index(op.f('ix_dim_bioid_user_id'), 'dim_bioid', ['user_id'], unique=True)
    op.create_table('dim_petition',
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('petition_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('petition_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vote_threshold', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('petitioner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['petitioner'], ['dim_user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facts_petition',
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('petition_id', sa.Uuid(), nullable=True),
    sa.Column('petition_affector_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['petition_affector_id'], ['dim_user.id'], ),
    sa.ForeignKeyConstraint(['petition_id'], ['dim_petition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facts_petition_action'), 'facts_petition', ['action'], unique=False)
    op.create_index(op.f('ix_facts_petition_petition_affector_id'), 'facts_petition', ['petition_affector_id'], unique=False)
    op.create_index(op.f('ix_facts_petition_petition_id'), 'facts_petition', ['petition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_facts_petition_petition_id'), table_name='facts_petition')
    op.drop_index(op.f('ix_facts_petition_petition_affector_id'), table_name='facts_petition')
    op.drop_index(op.f('ix_facts_petition_action'), table_name='facts_petition')
    op.drop_table('facts_petition')
    op.drop_table('item')
    op.drop_table('dim_petition')
    op.drop_index(op.f('ix_dim_bioid_user_id'), table_name='dim_bioid')
    op.drop_table('dim_bioid')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_dim_user_email'), table_name='dim_user')
    op.drop_table('dim_user')
    op.drop_table('dim_petitionthreshold')
    # ### end Alembic commands ###
